Repository bear-bear-bear/vanilla-instagram, pull requests merged in 2021-08, with the labels that each got.

#14 feat: 클라이언트 번들과 koa 연결, 정적 환경에서 hmr 과 유사한 효과를 낼 수 있게 해주는 미들웨어 작성
  client/app/entries/common.js
  client/app/pages/index.pug
  client/app/pages/test.pug
  client/app/styles/common/common.scss
  client/webpack.config.js
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/tsconfig.json
Labels: feature

#17 feat: 프론트엔드 웹팩 빌드 마무리 손질
  client/app/entries/index.js
  client/app/images/test.jpg
  client/app/images/test.png
  client/app/includes/header.pug
  client/app/pages/index.pug
  client/app/pages/test.pug
  client/app/styles/common/common.scss
  client/app/styles/common/defaults/_fonts.scss
  client/app/styles/common/templates/example-container.scss
  client/app/styles/index.scss
  client/app/templates/base.pug
  client/webpack.config.js
  server/src/index.ts
Labels: feature

#18 feat: 프런트엔드 app/ 구조 개발 친화적으로 변경, 관련 빌드 설정, alias 등 수정
  client/app/assets/fonts/open-sans-regular.woff2
  client/app/assets/images/js-logo.svg
  client/app/assets/images/test.png
  client/app/common/entry.js
  client/app/common/scripts/_loadingBeforePageLoad.js
  client/app/common/scripts/index.js
  client/app/common/styles/defaults/_fonts.scss
  client/app/common/styles/index.scss
  client/app/entries/index.js
  client/app/entries/test.js
  client/app/pages/home/entry.js
  client/app/pages/home/home.js
  client/app/pages/home/home.pug
  client/app/pages/home/home.scss
  client/app/pages/index.pug
  client/app/pages/test.pug
  client/app/pages/test/entry.js
  client/app/pages/test/test.js
  client/app/pages/test/test.pug
  client/app/pages/test/test.scss
  client/app/scripts/common/common.js
  client/app/styles/test.scss
  client/app/templates/base.pug
  client/app/templates/example-container/_entry.js
  client/app/templates/example-container/example-container.js
  client/app/templates/example-container/example-container.pug
  client/app/templates/example-container/example-container.scss
  client/jsconfig.json
  client/package.json
  client/page.config.js
  client/webpack.config.js
  client/webpack.parts.js
Labels: feature

#20 fix: stylelintrc 에서의 SCSS include mixin 인식 하지 못하던 문제 긴급 수정
  client/.stylelintrc
Labels: fix

#21 feat: 클라이언트 번들 script 비동기 로드 처리
  client/package-lock.json
  client/package.json
  client/webpack.config.js
  client/webpack.parts.js
Labels: refactor

#22 feat: SCSS 어디서든 varible과 mixin을 사용할 수 있도록 설정
  client/app/common/styles/defaults/__mixins__.scss
  client/app/common/styles/defaults/__variables__.scss
  client/app/templates/example-container/example-container.scss
  client/webpack.parts.js
  package-lock.json
  package.json
Labels: feature, fix

#27 design: 컬러변수 선언
  client/app/common/styles/defaults/__variables__.scss
Labels: feature

#28 !HOTFIX: 컬러 변수 잘못된 넘버링 수정
  client/app/common/styles/defaults/__mixins__.scss
  client/app/common/styles/defaults/__variables__.scss
  client/app/templates/example-container/example-container.scss
Labels: fix

#23 feat: footer 템플릿 추가
  client/app/common/styles/defaults/__variables__.scss
  client/app/common/styles/defaults/_reset.scss
  client/app/common/styles/index.scss
  client/app/templates/legal-policy/_entry.js
  client/app/templates/legal-policy/legal-policy.pug
  client/app/templates/legal-policy/legal-policy.scss
Labels: feature

#30 feat: 기존 swc 및 빌드, 개발 환경관련 라이브러리 정리 및 재설정
  server/.swcrc.json
  server/package-lock.json
  server/package.json
Labels: fix

#19 feat: login 페이지 생성
  client/app/assets/images/Doge.svg
  client/app/assets/images/image-cycle/first.jpg
  client/app/assets/images/iphone-viral.png
  client/app/pages/home/home.pug
  client/app/pages/login/entry.js
  client/app/pages/login/login.js
  client/app/pages/login/login.pug
  client/app/pages/login/login.scss
  client/app/templates/auth-form/_entry.js
  client/app/templates/auth-form/auth-form.js
  client/app/templates/auth-form/auth-form.pug
  client/app/templates/auth-form/auth-form.scss
  client/app/templates/login-iphone/_entry.js
  client/app/templates/login-iphone/login-iphone.js
  client/app/templates/login-iphone/login-iphone.pug
  client/app/templates/login-iphone/login-iphone.scss
  client/page.config.js
Labels: feature

#35 feat: 로그인페이지 responsive web 구현 - 백동재
  client/app/common/styles/defaults/__mixins__.scss
  client/app/pages/login/entry.js
  client/app/pages/login/login.pug
  client/app/pages/login/login.scss
  client/app/templates/auth-form/auth-form.scss
  client/app/templates/legal-policy/legal-policy.pug
  client/app/templates/legal-policy/legal-policy.scss
  client/app/templates/login-iphone/login-iphone.scss
Labels: feature

#41 feat: pug에서 hyphen이 들어간 페이지명을 사용할 수 있도록 설정
  client/app/pages/home/home.pug
  client/app/pages/test-test/entry.js
  client/app/pages/test-test/test-test.js
  client/app/pages/test-test/test-test.pug
  client/app/pages/test-test/test-test.scss
  client/page.config.js
  client/webpack.config.js
Labels: feature

#38 feat: 이슈 템플릿을 좀 더 가독성 좋게 변경
  .github/ISSUE_TEMPLATE/api-request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#36 feat: 회원가입 페이지 생성
  client/app/assets/images/Doge.svg
  client/app/common/styles/defaults/__mixins__.scss
  client/app/common/styles/defaults/__variables__.scss
  client/app/pages/home/home.pug
  client/app/pages/login/entry.js
  client/app/pages/login/login.pug
  client/app/pages/login/login.scss
  client/app/pages/sign-up/entry.js
  client/app/pages/sign-up/sign-up.pug
  client/app/pages/sign-up/sign-up.scss
  client/app/templates/auth-form/auth-form.pug
  client/app/templates/auth-form/auth-form.scss
  client/app/templates/footer/_entry.js
  client/app/templates/footer/footer.pug
  client/app/templates/footer/footer.scss
  client/app/templates/legal-policy/_entry.js
  client/app/templates/legal-policy/legal-policy.scss
  client/app/templates/login-iphone/login-iphone.scss
  client/page.config.js
Labels: feature

#39 fix: change position of module - closes #24
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
Labels: fix

#45 feat: ORM 관련 개발에 필요한 npm 패키지 사전 설치
  server/package-lock.json
  server/package.json
Labels: feature

#44 feat: 이메일인증페이지 생성
  client/app/assets/images/Email validate.png
  client/app/pages/email-validation/email-validation.pug
  client/app/pages/email-validation/email-validation.scss
  client/app/pages/email-validation/entry.js
  client/app/pages/home/home.pug
  client/app/templates/auth-form/auth-form.scss
  client/page.config.js
Labels: feature

#31 feat: 서버 실행 테스트 작성
  .github/workflows/node.js.yml
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/test/e2e/server.test.ts
  server/tsconfig.json
Labels: feature

#46 fix: 모든 요청 긍정 반환 미들웨어 사용
  server/src/index.ts
  server/test/e2e/server.test.ts
Labels: fix

#49 refactor: 이슈들 리펙터링및 가독성 개선
  client/app/common/styles/defaults/__mixins__.scss
  client/app/pages/email-validation/email-validation.pug
  client/app/pages/email-validation/entry.js
  client/app/pages/login/entry.js
  client/app/pages/login/login.pug
  client/app/pages/login/login.scss
  client/app/pages/sign-up/entry.js
  client/app/pages/sign-up/sign-up.pug
  client/app/pages/sign-up/sign-up.scss
  client/app/templates/auth-container/_entry.js
  client/app/templates/auth-container/auth-container.js
  client/app/templates/auth-container/auth-container.pug
  client/app/templates/auth-container/auth-container.scss
  client/app/templates/auth-form/_entry.js
  client/app/templates/footer/footer.pug
  client/app/templates/footer/footer.scss
  client/app/templates/login-iphone/_entry.js
  client/app/templates/login-iphone/login-iphone.js
  client/app/templates/login-iphone/login-iphone.pug
  client/app/templates/login-iphone/login-iphone.scss
Labels: fix, refactor

#51 feat: 벡엔드 데이터베이스 연결 및 DB 생성 스크립트 명령 추가
  .github/workflows/node.js.yml
  server/.env.example
  server/.eslintrc.js
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/config/config.ts
  server/src/index.ts
  server/src/models/index.ts
  server/src/models/sequelize.ts
  server/test/e2e/server.test.ts
Labels: feature

#52 feat: 회원가입 인증관련 페이지 추가 및 수정
  client/app/assets/images/Doge.svg
  client/app/assets/images/Email validate.png
  client/app/assets/images/iphone.png
  client/app/common/styles/defaults/__mixins__.scss
  client/app/pages/home/home.pug
  client/app/pages/login/login.scss
  client/app/pages/sign-up/sign-up.pug
  client/app/pages/verification/entry.js
  client/app/pages/verification/verification.pug
  client/app/pages/verification/verification.scss
  client/page.config.js
Labels: feature, refactor

#53 !HOTFIX: .js 확장자 생략 시 babel이 해당 모듈을 인식하지 못하는 문제
  client/.eslintrc.js
  client/app/common/entry.js
  client/app/common/scripts/index.js
  client/app/pages/home/entry.js
  client/app/pages/login/entry.js
  client/app/pages/suggested-feed/entry.js
  client/app/pages/test-test/entry.js
  client/app/templates/auth-container/_entry.js
  client/app/templates/container/_entry.js
  client/app/templates/example-container/_entry.js
  client/webpack.config.js
Labels: fix

#54 feat: DB 모델링 작업
  server/.env.example
  server/src/config/config.ts
  server/src/models/_sequelize.ts
  server/src/models/admin.ts
  server/src/models/ban.ts
  server/src/models/comment.ts
  server/src/models/hashtag.ts
  server/src/models/image.ts
  server/src/models/index.ts
  server/src/models/post.ts
  server/src/models/user.ts
  server/test/e2e/server.test.ts
Labels: feature

#55 feat: SMS 관련 모듈 설치, 환경 변수 설정
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/lib/sendSMS.example.ts
Labels: feature

#57 !HOTFIX: 확장자 입력 오류로 인한 컴파일 에러 수정
  client/app/pages/suggested-feed/entry.js
Labels: fix

#56 feat: 회원가입, 로그인 관련 타입과 dto(with validation) 작성
  server/.eslintrc.js
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/dto/auth.dto.ts
  server/tsconfig.json
  server/typings/auth.ts
Labels: feature

#59 feat: phone 번호 unique 제약 삭제
  server/src/models/user.ts
Labels: feature

#62 feat: 백엔드 회원가입 로직 개발
  client/app/common/entry.js
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/config.ts
  server/src/controllers/hot.ts
  server/src/controllers/sms.ts
  server/src/controllers/user.ts
  server/src/lib/createDatabase.ts
  server/src/lib/sendSMS.example.ts
  server/src/routes/hot.ts
  server/src/routes/index.ts
  server/src/routes/sms.ts
  server/src/routes/user.ts
  server/test/mock-data/join-fields.json
  server/test/unit/example.test.js
  server/typings/sms.dto.ts
  server/typings/user.dto.ts
  server/typings/user.ts
Labels: feature, refactor

#63 feat: 백엔드 without extension url 적용으로 경로에서 .html 확장자 제거
  client/webpack.config.js
Labels: feature

#64 feat: 에러 핸들링 보완 및 로그 기능 추가, #62 누락사항 복구
  server/src/app.ts
  server/src/config/config.ts
  server/src/controllers/sms.ts
  server/src/controllers/user.ts
  server/src/lib/createDatabase.ts
  server/src/lib/saveErrorMessage.ts
  server/src/routes/index.ts
  server/src/routes/sms.ts
  server/typings/sms.dto.ts
  server/typings/sms.ts
  server/typings/user.dto.ts
Labels: feature, fix

#65 feat: 회원가입 관련 에러 사항 수정, 예외 케이스 처리 로직 추가
  server/src/app.ts
  server/src/controllers/sms.ts
  server/src/controllers/user.ts
  server/src/lib/saveErrorMessage.ts
  server/tsconfig.json
  server/typings/sms.ts
  server/typings/user.ts
Labels: feature, fix
